"""
JWT Authentication dependencies for FastAPI.

This module provides dependency functions for verifying JWT tokens
sent from the Next.js frontend and extracting the authenticated user ID.

Security Model:
- JWT tokens are generated by Next.js using a shared secret
- Tokens are short-lived (5 minutes expiration)
- Tokens contain user_id in the 'sub' claim
- Backend verifies signature and extracts user_id
"""

import logging
from typing import Optional

from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from jose import JWTError, jwt
from app.config import get_settings

logger = logging.getLogger(__name__)

# HTTP Bearer token scheme
security = HTTPBearer(auto_error=False)


async def get_current_user(
    credentials: Optional[HTTPAuthorizationCredentials] = Depends(security)
) -> Optional[str]:
    """
    Verify JWT token and extract user_id.
    
    This dependency can be made optional by setting auto_error=False
    in the HTTPBearer scheme above. Returns None if no token provided.
    
    Args:
        credentials: HTTP Authorization header with Bearer token
        
    Returns:
        User ID string from the JWT 'sub' claim
        
    Raises:
        HTTPException 401: If token is invalid, expired, or user_id missing
    """
    if credentials is None:
        # No token provided - this is OK for public endpoints
        # Protected endpoints should use get_current_user_required instead
        return None
    
    token = credentials.credentials
    settings = get_settings()
    
    if not settings.JWT_SECRET:
        logger.error("[AUTH] JWT_SECRET not configured")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Authentication not configured properly"
        )
    
    try:
        # Verify JWT signature and extract payload
        payload = jwt.decode(
            token,
            settings.JWT_SECRET,
            algorithms=[settings.JWT_ALGORITHM]
        )
        
        # Extract user_id from 'sub' claim (standard JWT subject field)
        user_id = payload.get("sub")
        
        if not user_id:
            logger.warning("[AUTH] Token missing 'sub' claim")
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token: missing user ID"
            )
        
        logger.debug("[AUTH] Successfully verified token for user: %s", user_id)
        return user_id
        
    except jwt.ExpiredSignatureError:
        logger.warning("[AUTH] Token expired")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token expired"
        )
    except jwt.InvalidTokenError as e:
        logger.warning("[AUTH] Invalid token: %s", str(e))
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token"
        )
    except Exception as e:
        logger.error("[AUTH] Unexpected error during token verification: %s", e)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Authentication error"
        )


async def get_current_user_required(
    current_user: Optional[str] = Depends(get_current_user)
) -> str:
    """
    Require authentication. Returns user_id or raises 401.
    
    Use this dependency for endpoints that MUST have an authenticated user.
    
    Args:
        current_user: User ID from get_current_user (can be None)
        
    Returns:
        User ID string (guaranteed to be non-None)
        
    Raises:
        HTTPException 401: If no token provided or token invalid
    """
    if current_user is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication required"
        )
    return current_user


# Optional: Role-based access (for future use)
async def get_current_user_with_role(
    current_user: str = Depends(get_current_user_required)
) -> tuple[str, list[str]]:
    """
    Extract user_id and roles from JWT.
    
    For future use: If your JWT contains a 'roles' claim,
    this dependency can extract both user_id and roles.
    
    Args:
        current_user: User ID from get_current_user_required
        
    Returns:
        Tuple of (user_id, list of roles)
    """
    # This is a placeholder for future role-based access
    # You would need to modify get_current_user to return the full payload
    # instead of just the user_id
    return current_user, []
